import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";

import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Shmel Gallery",
  description: "Generated by one of loyal owners",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}flex flex-col gap-4`}>
      <body className={'font-sans ${inter.variable}'}>
        
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
